### ISSUE TITLE
missing example of WebClient

### ISSUE THREAD

**Issue by mrvbicakci** [smartface/apidocs-content#13]
I searched for "webclient" in docs.smartface.io and in docs.smartfacecloud.io. 
The old docs found an example about SMF.Net.WebClient Constructor : 
![olddocssearch](https://cloud.githubusercontent.com/assets/12133528/9760284/6247b778-56fc-11e5-914a-0f240e43acbc.PNG)

But this example doesn't exist in new docs (or I couldn't find it I don't know). 
![newdocssearch](https://cloud.githubusercontent.com/assets/12133528/9760286/63db65b2-56fc-11e5-8535-bc4c01a46cb8.PNG)

**Comment by alperozisik** [comment]
WebClient hidden
